# Generated by Django 4.1.7 on 2023-03-07 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_account_alter_follow_book_alter_follow_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="user",
            new_name="account",
        ),
    ]
