# Generated by Django 4.1.7 on 2023-03-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_first_name_alter_account_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
