# Generated by Django 4.1.7 on 2023-03-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="punishment",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
