# Generated by Django 4.1.7 on 2023-03-09 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0003_alter_copy_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="copy",
            old_name="account",
            new_name="loans",
        ),
    ]
