# Generated by Django 4.1.7 on 2023-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0004_rename_account_copy_loans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
